# Conclusions {-}

Now that we have reached the final chapter of this book, we want to discuss the main limitations and future work in the area of complex-valued statistics and econometrics. We focused this book on the technical side of modelling with complex-valued regressions, discussing the estimation methods, elements of correlation analysis and the main aspects of the regression analysis. We briefly discussed the complex ARIMA model, only touching on some of the important properties of it. But there is much more left outside.

For example, we mentioned that complex-valued models share some properties with the multivariate ones, such as Vector AR (VAR). This means that we can use the tools developed for those models for the complex-valued ones with minor modifications. For instance, we did not discuss how to calculate Impulse Response Function, which is widely used for analysis of effects based on VAR in Economics and Marketing Analytics. We expect that these tools can be transferred to the complex-valued models easily, but they lie outside of the scope of this monograph and can be considered as a future work.

Furthermore, a curious reader might wonder what to do when we are interested in modelling more than two variables at the same time. The first instinct would be to switch to the multivariate models, such as VAR(p). But the main issue of those models is the high dimensionality. For example, VAR(p) on 10 time series requires the estimation of $p \times 10^2$ parameters, which is not a simple task. However, @SvetunkovSergey **(need reference here!!!)** has developed a solution in this situation which involves complex variables. The model based on this is called vector cARIMA, VcARIMA(p,d,q) and involves stacking several complex response variables in a vector. This model is currently studied, and Sergey Svetunkov is preparing a paper explaining its properties, and showing how it can be used for time series analysis and in forecasting.

Moreover, as discussed in this book several times, some of the largest benefits of complex variables arise when a non-linear model is considered, e.g. a log-log model. We have discussed what happens with the cLR in this situation (Subsection \@ref(assumptionsSpecificationTransformation) and Section \@ref(DynamicTrend)), but we have not yet study how the cARIMA behaves in this situation. We expect that it should be able to capture non-linear dynamics, which would be beneficial when applied to large samples of data, such as, for example, in energy domain.

Finally, we focused this monograph on complex-valued models that have two real valued variables in the complex response one. But this is not the only way of modelling using complex variables. @Svetunkov2012 **(+ reference for papers from SPb team)** discussed some other ways of modelling which lie outside of this monograph.

Overall, we think that complex-valued modelling enriches the instrumental base of analysts and forecasters and allows modelling complicated processes in a more compact way. The authors plan to continue working in this direction and if you find the models and the R code developed for this monograph useful, we would be glad to hear from you. You can visit our website [www.svetunkov.com](https://svetunkov.com) and get in touch with us using one of the ways you find convenient.


<!-- In addition, the students and colleagues of Sergey Svetunkov have developed several other models relying on the theory of complex variables. These models all lie outside of the scope of this book, but they are worth mentioning for completeness. -->

<!-- The first one is the complex AR model with the error term in the imaginary part: -->
<!-- \begin{equation} -->
<!--     y_t + i \xi_t = \sum_{j=1}^p (b_{j,r} + i b_{j,i}) (y_{t-j} + i \epsilon_{t-j}) + \epsilon_{t} , -->
<!--     (\#eq:ConclusionsCARE) -->
<!-- \end{equation} -->
<!-- where $\xi_t$ is a fuzzy component which does not have any specific meaning. This model is inspired by the Complex Exponential Smoothing by @Svetunkov2022, and it can be shown (after opening the brackets) that its real part is equivalent to the ARMA(p,p) model. On its own the model does not have any special properties, but it gives the rise to more complicated models, for example, where the imaginary part is transformed or substituted by some other variables. In case of the transformation, the model exhibits some non-linearity that is not considered by the conventional ARMA: -->
<!-- \begin{equation} -->
<!--     y_t + i \xi_t = \sum_{j=1}^p (b_{j,r} + i b_{j,i}) (y_{t-j} + i f(\epsilon_{t-j})) + \epsilon_{t} , -->
<!--     (\#eq:ConclusionsCARNE) -->
<!-- \end{equation} -->
<!-- where $f(\cdot)$ is some non-linear function. In this case, the impact of the error term on the actual value becomes non-linear. -->


<!-- Complex AR with differences -->

